[package]
name = "pmc"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://lab.themackabu.dev/crates/pmc"
description = "Process management controller"

[dependencies]
clap = "4.4.8"
log = "0.4.20"
toml = "0.8.8"
cxx = "1.0.110"
serde = "1.0.192"
ratatui = "0.24.0"
macros-rs = "0.4.0"
termcolor = "1.4.0"
crossterm = "0.27.0"
serde_json = "1.0.108"
serde_derive = "1.0.192"
pretty_env_logger = "0.5.0"
clap-verbosity-flag = "2.1.0"

[build-dependencies]
cxx-build = "1.0.110"
