[package]
name = "pmc"
version = "1.6.3"
edition = "2021"
license = "MIT"
repository = "https://lab.themackabu.dev/self/pmc"
description = "PMC is a simple and easy to use PM2 alternative"

[dependencies]
clap = "4.4.8"
log = "0.4.20"
toml = "0.8.8"
home = "0.5.5"
warp = "0.3.6"
cxx = "1.0.110"
bytes = "1.5.0"
regex = "1.10.2"
libc = "0.2.150"
anyhow = "1.0.75"
colored = "2.0.4"
macros-rs = "0.5.0"
termcolor = "1.4.0"
rmp-serde = "1.1.2"
once_cell = "1.18.0"
static_dir = "0.2.0"
env_logger = "0.10.1"
merkle_hash = "3.5.0"
lazy_static = "1.4.0"
prometheus = "0.13.3"
serde_json = "1.0.108"
simple-logging = "2.0.2"
utoipa-rapidoc = "1.0.0"
pretty_env_logger = "0.5.0"
clap-verbosity-flag = "2.1.0"
global_placeholders = "0.1.0"
tokio = { version = "1.34.0", features = ["full"] }
psutil = { version = "3.2.2", features = ["serde"] }
tabled = { version = "0.14.0", features = ["color"] }
chrono = { version = "0.4.23", features = ["serde"] }
serde = { version = "1.0.192", features = ["derive"] }
utoipa = { version = "4.1.0", features = ["serde_yaml"] }

[build-dependencies]
tar = "0.4.40"
chrono = "0.4.23"
flate2 = "1.0.28"
cxx-build = "1.0.110"
reqwest = { version = "0.11.22", features = ["blocking"] }
