import = [".maid/build.toml", ".maid/server.toml"]

[project]
name = "pmc"
version = "1.6.0"

[tasks]
clean = { script = ["rm -rf bin", "mkdir bin"] }
api = { script = ["maid install -q", "pmc daemon start --api"] }
webui = { script = ["maid install -q", "pmc daemon start --webui"] }

[tasks.build]
depends = ["clean"]
script = [
   "cargo zigbuild --release", 
   "cp target/release/pmc bin/pmc"
]

[tasks.build.cache]
path = "src"
target = ["bin/pmc"]

[tasks.install]
script = [
   "killall pmc",
   "maid build -q", 
   "sudo cp bin/pmc /usr/local/bin",
   "echo Copied binary!"
]