[project]
name = "pmc"
version = "1.1.2"

[tasks]
clean = { script = ["rm -rf bin", "mkdir bin"] }

[tasks.build]
depends = ["clean"]
script = [
   "cargo zigbuild --release", 
   "cp target/release/pmc bin/pmc"
]

[tasks.build.cache]
path = "src"
target = ["bin/pmc"]

[tasks.install]
script = [
   "maid build -q", 
   "sudo cp bin/pmc /usr/local/bin",
    "echo Copied binary!"
]
