[env]
VERSION='1.7.1'

[tasks.build_all]
info = "build all"
script = [
   # install packages
   "apt-get update -yqq",
   "apt-get install zip clang llvm -yqq",

   # setup build
   "mkdir build",
   "export CC=\"/usr/bin/clang\"",
   "export CXX=\"/usr/bin/clang++\"",

   # build linux (x86_64)
   "cargo zigbuild -r --color always",
   "mv target/release/pmc build/pmc",
   "zip build/pmc_%{env.VERSION}_linux_amd64.zip build/pmc",
   "rm build/pmc",
   
   # # build macos (x86_64)
   # "cargo zigbuild -r --target x86_64-apple-darwin --color always", 
   # "mv target/x86_64-apple-darwin/release/pmc build/pmc",
   # "zip build/pmc_%{env.VERSION}_darwin_amd64.zip build/pmc",
   # "rm build/pmc",
   # 
   # # build macos (aarch64)
   # "cargo zigbuild -r --target aarch64-apple-darwin --color always", 
   # "mv target/aarch64-apple-darwin/release/pmc build/pmc",
   # "zip build/pmc_%{env.VERSION}_darwin_arm.zip build/pmc",
   # "rm build/pmc",
   
   # post build
   "ls -sh build",
]

[tasks.build_all.remote]
silent = false
exclusive = true
shell = "/bin/bash"
image = "themackabu/rust:zigbuild-1.75.0"
push = ["src", "lib", "Cargo.toml", "Cargo.lock", "build.rs"]
pull = "build"
